/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TrackInfo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'blob' : ExternalBlob,
  'artist' : IDL.Text,
});
export const PlaylistInfo = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'trackIds' : IDL.Vec(IDL.Nat),
});
export const SessionInfo = IDL.Record({
  'lastPosition' : IDL.Nat,
  'lastTrackId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addTrack' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [TrackInfo],
      [],
    ),
  'addTrackToPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'createPlaylist' : IDL.Func([IDL.Text], [PlaylistInfo], []),
  'deletePlaylist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTrack' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getPlaylist' : IDL.Func([IDL.Nat], [IDL.Opt(PlaylistInfo)], ['query']),
  'getSession' : IDL.Func([], [SessionInfo], ['query']),
  'getTrack' : IDL.Func([IDL.Nat], [IDL.Opt(TrackInfo)], ['query']),
  'listPlaylists' : IDL.Func([], [IDL.Vec(PlaylistInfo)], ['query']),
  'listTracks' : IDL.Func([], [IDL.Vec(TrackInfo)], ['query']),
  'removeTrackFromPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'renamePlaylist' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'saveSession' : IDL.Func([IDL.Opt(IDL.Nat), IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TrackInfo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'blob' : ExternalBlob,
    'artist' : IDL.Text,
  });
  const PlaylistInfo = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'trackIds' : IDL.Vec(IDL.Nat),
  });
  const SessionInfo = IDL.Record({
    'lastPosition' : IDL.Nat,
    'lastTrackId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addTrack' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [TrackInfo],
        [],
      ),
    'addTrackToPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'createPlaylist' : IDL.Func([IDL.Text], [PlaylistInfo], []),
    'deletePlaylist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTrack' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getPlaylist' : IDL.Func([IDL.Nat], [IDL.Opt(PlaylistInfo)], ['query']),
    'getSession' : IDL.Func([], [SessionInfo], ['query']),
    'getTrack' : IDL.Func([IDL.Nat], [IDL.Opt(TrackInfo)], ['query']),
    'listPlaylists' : IDL.Func([], [IDL.Vec(PlaylistInfo)], ['query']),
    'listTracks' : IDL.Func([], [IDL.Vec(TrackInfo)], ['query']),
    'removeTrackFromPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'renamePlaylist' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'saveSession' : IDL.Func([IDL.Opt(IDL.Nat), IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };