/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PlaylistInfo {
  'id' : bigint,
  'name' : string,
  'trackIds' : Array<bigint>,
}
export interface SessionInfo {
  'lastPosition' : bigint,
  'lastTrackId' : [] | [bigint],
}
export interface TrackInfo {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'blob' : ExternalBlob,
  'artist' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addTrack' : ActorMethod<[string, string, bigint, ExternalBlob], TrackInfo>,
  'addTrackToPlaylist' : ActorMethod<[bigint, bigint], boolean>,
  'createPlaylist' : ActorMethod<[string], PlaylistInfo>,
  'deletePlaylist' : ActorMethod<[bigint], boolean>,
  'deleteTrack' : ActorMethod<[bigint], boolean>,
  'getPlaylist' : ActorMethod<[bigint], [] | [PlaylistInfo]>,
  'getSession' : ActorMethod<[], SessionInfo>,
  'getTrack' : ActorMethod<[bigint], [] | [TrackInfo]>,
  'listPlaylists' : ActorMethod<[], Array<PlaylistInfo>>,
  'listTracks' : ActorMethod<[], Array<TrackInfo>>,
  'removeTrackFromPlaylist' : ActorMethod<[bigint, bigint], boolean>,
  'renamePlaylist' : ActorMethod<[bigint, string], boolean>,
  'saveSession' : ActorMethod<[[] | [bigint], bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];